services:
  postgres:
    image: postgres
    container_name: events_db
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
